# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator
# token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EU_cal <- function(cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, nsample, N, n1, n2, 
    parallel, ncore) {
    .Call(`_Mfrailty_EU_cal`, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, nsample, 
        N, n1, n2, parallel, ncore)
}

Ef_cal <- function(f, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, nsample, N, n1, n2, 
    parallel, ncore) {
    .Call(`_Mfrailty_Ef_cal`, f, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, nsample, 
        N, n1, n2, parallel, ncore)
}

Ef1f2_cal <- function(f1, f2, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, nsample, 
    N, n1, n2, parallel, ncore) {
    .Call(`_Mfrailty_Ef1f2_cal`, f1, f2, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, 
        nsample, N, n1, n2, parallel, ncore)
}

ObslogL <- function(haz1, haz2, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, nsample, 
    N, n1, n2, parallel, ncore) {
    .Call(`_Mfrailty_ObslogL`, haz1, haz2, cumsum1, cumsum2, dc, ww1, ww2, vv1, vv2, 
        nsample, N, n1, n2, parallel, ncore)
}

EU_cal_ts <- function(cumsum, sig2, margins, w, v, nsample, N, n, parallel, ncore) {
    .Call(`_Mfrailty_EU_cal_ts`, cumsum, sig2, margins, w, v, nsample, N, n, parallel, 
        ncore)
}

Ef_cal_ts <- function(f, cumsum, sig2, margins, w, v, nsample, N, n, parallel, ncore) {
    .Call(`_Mfrailty_Ef_cal_ts`, f, cumsum, sig2, margins, w, v, nsample, N, n, parallel, 
        ncore)
}

ObslogL_ts <- function(haz, cumsum, sig2, margins, w, v, nsample, N, n, parallel, 
    ncore) {
    .Call(`_Mfrailty_ObslogL_ts`, haz, cumsum, sig2, margins, w, v, nsample, N, n, 
        parallel, ncore)
}

